In [1]:
import functions

pre_aloc = functions.carregamento(
path='C:/Users/70089581/Kantar/BKO - dados-ops/do_preal_fornecedor/ref_prealoc',
prefixo='pre'
)

trocas = {
'{GroupId}' : 'UserPS',
'{IndividualId}' : 'individual-id',
'{CreationTimeStamp}' : 'created_at',
'Origen' : 'Origen_GPM'
}

pre_aloc.rename(columns=trocas, inplace=True)

In [2]:
pre_aloc.UserPS.nunique()

16000

In [3]:
import functions

troca = functions.carregamento(
path='C:/Users/70089581/Kantar/BKO - dados-ops/do_preal_fornecedor/ref_troca',
prefixo='ref_'
)

trocas = {
'{GroupId}' : 'UserPS',
'{IndividualId}' : 'individual-id',
'{CreationTimeStamp}' : 'created_at',
'Origen' : 'Origen_GPM'
}

troca.rename(columns=trocas, inplace=True)

In [4]:
src = [552254628
]

In [5]:
pre_aloc.Origen_GPM = pre_aloc.Origen_GPM.replace(22,'22 - Centro-Oeste')
pre_aloc.Origen_GPM = pre_aloc.Origen_GPM.replace(21,'21 - Interior SP')
pre_aloc.Origen_GPM = pre_aloc.Origen_GPM.replace(23,'23 - Resto BR')
pre_aloc.Origen_GPM = pre_aloc.Origen_GPM.replace(20,'20 - Nordeste')



pre_aloc.Origen_GPM = pre_aloc.Origen_GPM.replace(4,'4 - IHS')
pre_aloc.Origen_GPM = pre_aloc.Origen_GPM.replace('IHS','4 - IHS')

In [6]:
pre_aloc.Origen_GPM.value_counts()

Origen_GPM
4 - IHS              10000
22 - Centro-Oeste     1500
21 - Interior SP      1500
20 - Nordeste         1500
23 - Resto BR         1500
Name: count, dtype: int64

In [8]:
pre_aloc.loc[pre_aloc['UserPS'].isin(src)]

         UserPS  individual-id        created_at Origen_GPM
5527  552254628  0552254628-01  27/04/2026 09:33    4 - IHS

In [ ]:
troca.loc[troca['UserPS'    ].isin(src)]

Empty DataFrame
Columns: [UserPS, individual-id, created_at, Data_da_retirada,  , Unnamed: 5]
Index: []

In [5]:
import time

import functions

pre_aloc = functions.carregamento(
path='C:/Users/70089581/Kantar/BKO - dados-ops/do_preal_fornecedor/ref_prealoc',
prefixo='pre'
)

trocas = {
'{GroupId}' : 'UserPS',
'{IndividualId}' : 'individual-id',
'{CreationTimeStamp}' : 'created_at',
'Origen' : 'Origen_GPM'
}

pre_aloc.rename(columns=trocas, inplace=True)

pre_aloc['UserPS'] = pre_aloc['UserPS'].astype(str)

print("qty prealoca: ",pre_aloc.shape[0])

df_cldar = functions.carregamento(
path='C:/Users/70089581/Kantar/BKO - dados-ops/do_calendario_fiscal',
prefixo='do_cal'
)

rep7 = functions.carregamento(
path='C:/Users/70089581/Kantar/BKO - dados-ops/do_rep7/bruto',
prefixo='Brasil-Reporte-7'
)
print("step 1 - Pre-Filtro-Vigente : ", rep7.DiaDeCompra.isna().value_counts())

rep7, inicio, fim = functions.filtrar_periodo_vigente(
rep7, 
df_cldar,
coluna_data='DiaDeCompra'
)
print("step 2 - Pos-Filtro-Vigente : ", rep7.DiaDeCompra.isna().value_counts())
rep7_mirror = rep7.copy()

rep7 = normalize(rep7)

print("step 3 - Pos-Filtro-Normaliza : ", rep7.DiaDeCompra.isna().value_counts())

qty prealoca:  11000
step 1 - Pre-Filtro-Vigente :  DiaDeCompra
False    145089
Name: count, dtype: int64
QTD dados original qmob: 145089
Coluna data: DiaDeCompra
Período encontrado: 2026-05-25 00:00:00 até 2026-06-23 00:00:00
QTD após filtro no periodo produtivo atual: 3470
step 2 - Pos-Filtro-Vigente :  DiaDeCompra
False    3470
Name: count, dtype: int64
Dimensão entrada saida iguais

step 3 - Pos-Filtro-Normaliza :  DiaDeCompra
False    3470
Name: count, dtype: int64

In [40]:
rep7

,Pais,Prefijo,Origen,UserPS,IdIndividuo,DuenadeCasa,DiaDeCompra,NumCompras,OrigenGPM,Unnamed: 9,DiaDeCompra_raw,mes_ref,ano_ref,len_us
3706,Brasil,55,Variable Origen no instruida en GPM,550405209,1,0,NaT,1,0,NaN,2026-05-26,NaT,NaT,9.0
5027,Brasil,55,Variable Origen no instruida en GPM,551013412,1,0,NaT,14,0,NaN,2026-05-26,NaT,NaT,9.0
5066,Brasil,55,Variable Origen no instruida en GPM,551013457,1,0,NaT,2,0,NaN,2026-05-25,NaT,NaT,9.0
5123,Brasil,55,Variable Origen no instruida en GPM,551017220,1,0,NaT,6,0,NaN,2026-05-25,NaT,NaT,9.0
5136,Brasil,55,Variable Origen no instruida en GPM,551017232,1,0,NaT,1,0,NaN,2026-05-25,NaT,NaT,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99211,Brasil-OOH,OOH,Variable Origen no instruida en GPM,br0552078560-01,1,0,NaT,1,0,NaN,2026-05-26,NaT,NaT,15.0
99250,Brasil-OOH,OOH,Variable Origen no instruida en GPM,br0552079654-01,1,0,NaT,1,0,NaN,2026-05-26,NaT,NaT,15.0
99265,Brasil-OOH,OOH,Variable Origen no instruida en GPM,br0552081766-01,1,0,NaT,2,0,NaN,2026-05-26,NaT,NaT,15.0
99281,Brasil-OOH,OOH,Variable Origen no instruida en GPM,br0552081833-01,1,0,NaT,1,0,NaN,2026-05-26,NaT,NaT,15.0
99294,Brasil-OOH,OOH,Variable Origen no instruida en GPM,br0552083227-01,1,0,NaT,8,0,NaN,2026-05-25,NaT,NaT,15.0

In [41]:
rep7_mirror

,Pais,Prefijo,Origen,UserPS,IdIndividuo,DuenadeCasa,DiaDeCompra,NumCompras,OrigenGPM,Unnamed: 9
46,Brasil,55,Variable Origen no instruida en GPM,55000001,1,0,2026-05-25,10,0,NaN
47,Brasil,55,Variable Origen no instruida en GPM,55000001,1,0,2026-05-26,9,0,NaN
238,Brasil,55,Variable Origen no instruida en GPM,55000011,1,0,2026-05-25,2,0,NaN
239,Brasil,55,Variable Origen no instruida en GPM,55000011,1,0,2026-05-25,1,0,NaN
240,Brasil,55,Variable Origen no instruida en GPM,55000011,1,0,2026-05-26,8,0,NaN
...,...,...,...,...,...,...,...,...,...,...
144737,Brasil-PNI,55,Variable Origen no instruida en GPM,552093763,1,0,2026-05-26,1,0,NaN
144817,Brasil-PNI,55,Variable Origen no instruida en GPM,552098247,1,0,2026-05-26,2,0,NaN
145003,Brasil-PNI,55,Variable Origen no instruida en GPM,55351177,1,0,2026-05-26,5,0,NaN
145010,Brasil-PNI,55,Variable Origen no instruida en GPM,55352293,1,0,2026-05-25,7,0,NaN
145058,Brasil-PNI,55,Variable Origen no instruida en GPM,55513918,1,0,2026-05-26,1,0,NaN

In [ ]:
import os

system.start()